#!/bin/bash

InputFile=/home/parisa/ipaddress
Temporary=/tmp/ping_result
logFile=/home/parisa/logfile

Today=`date +%Y-%m-%d`

while read line
do
    truncate -s0 $Temporary
    ping -c 3 -W 3 $line > $Temporary
    Result=$(cat $Temporary | grep "3 packets transmitted" | awk -F',' '{print $3 " , " $4}')
    if [[ $Result != "100% packet loss" ]]; then
            Time=$(cat $Temporary | grep "rtt min/avg/max/mdev" | awk -F' = ' '{print $2}')
            echo $Today"|"$line"|"$Result"|"$Time >> $logFile
    else
            echo $Today"|"$line"|"$Result >> $logFile
    fi
done < $InputFile
