#!/bin/bash

read -p "please enter a number: " NUMBER

if [ $NUMBER -gt 10 ]; then
        echo "The number is larger than 10!"
elif [ $NUMBER -eq 10 ]; then
        echo "The number is equal 10!"
elif [ $NUMBER -lt 10 ]; then
        echo "The number is smallest 10!"
else
        echo "The input is not valid"
fi
